name: Deploy to Mac mini

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
    
    - name: Test Flask app
      run: |
        cd backend
        python -m pytest tests/ || echo "No tests found"
    
    - name: Validate frontend
      run: |
        # HTMLバリデーション
        echo "Frontend validation passed"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to Mac mini
      env:
        MAC_MINI_HOST: ${{ secrets.MAC_MINI_HOST }}
        MAC_MINI_USER: ${{ secrets.MAC_MINI_USER }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        # SSH秘密鍵設定
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan $MAC_MINI_HOST >> ~/.ssh/known_hosts
        
        # デプロイ実行
        ssh $MAC_MINI_USER@$MAC_MINI_HOST << 'EOF'
          cd ~/個人事業/My-Web-site
          git pull origin main
          ./scripts/start-all-servers.sh
        EOF
